/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dl5eu
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DL5EU_API_H
#define INCLUDED_DL5EU_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dl5eu_EXPORTS
#define DL5EU_API __GR_ATTR_EXPORT
#else
#define DL5EU_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DL5EU_API_H */
