/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvbt_ofdm_synchronization.h) */
/* BINDTOOL_HEADER_FILE_HASH(94b5fe7896a6361ea41cdbfb654c1872)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dl5eu/dvbt_ofdm_synchronization.h>
// pydoc.h is automatically generated in the build directory
#include <dvbt_ofdm_synchronization_pydoc.h>

void bind_dvbt_ofdm_synchronization(py::module& m)
{

    using dvbt_ofdm_synchronization = gr::dl5eu::dvbt_ofdm_synchronization;


    py::class_<dvbt_ofdm_synchronization,
               gr::block,
               gr::basic_block,
               std::shared_ptr<dvbt_ofdm_synchronization>>(
        m, "dvbt_ofdm_synchronization", D(dvbt_ofdm_synchronization))

        .def(py::init(&dvbt_ofdm_synchronization::make),
             py::arg("transmission_mode"),
             py::arg("guard_interval"),
             py::arg("snr"),
             py::arg("interpolate"),
             D(dvbt_ofdm_synchronization, make))


        ;
}
